swagger: '2.0'
info:
  title: Data Operations API
  description: API to manage data operations through Cloud Functions
  version: '1.0.0'
host: 'us-central1.cloudfunctions.net'
schemes:
  - https
paths:
  /load_csv:
    post:
      operationId: loadCSV
      summary: Load data from CSV files into BigQuery
      x-google-backend:
        address: https://us-central1-{{ PROJECT_ID }}.cloudfunctions.net/gc_csv_2_bq
      responses:
        '200':
          description: Data loaded successfully
      security:
        - oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
  /insert_data:
    post:
      operationId: insertData
      summary: Insert data into BigQuery tables
      x-google-backend:
        address: https://us-central1-{{ PROJECT_ID }}.cloudfunctions.net/append_data
      responses:
        '200':
          description: Data inserted successfully
      security:
        - oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
securityDefinitions:
  oauth2:
    type: oauth2
    authorizationUrl: "https://accounts.google.com/o/oauth2/auth"
    tokenUrl: "https://oauth2.googleapis.com/token"
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/userinfo.email': 'View your email address'
    jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
