name: Deploy project

on:
  push:
    branches:
      - master

jobs:
  deploy-csv-to-bigquery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy CSV to BigQuery Cloud Function
        run: |
          gcloud functions deploy gc_csv_2_bq \
            --entry-point csv_to_bigquery \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region us-central1 \
            --source ./load_data \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}

  deploy-append-data:
    needs: deploy-csv-to-bigquery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Append Data Cloud Function
        run: |
          gcloud functions deploy append_data \
            --entry-point insert_data \
            --runtime python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region us-central1 \
            --source ./api \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
  
  deploy-api-gateway:
    needs: deploy-append-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Prepare OpenAPI configuration file
        run: |
          sed "s/{{ PROJECT_ID }}/${{ secrets.GCP_PROJECT_ID }}/g" openapi2-functions_template.yaml > openapi2-functions.yaml

      - name: Check if API exists
        id: api_exists
        run: |
          if gcloud api-gateway apis describe data-migration-api --project=${{ secrets.GCP_PROJECT_ID }}; then
            echo "API exists."
            echo "api_exists=true" >> $GITHUB_ENV
          else
            echo "API does not exist."
            echo "api_exists=false" >> $GITHUB_ENV
          fi

      - name: Create API if not exists
        if: env.api_exists == 'false'
        run: |
          gcloud api-gateway apis create data-migration-api --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Create API Config
        run: |
          gcloud api-gateway api-configs create data-migration-config-${{ github.run_number }} \
            --api=data-migration-api \
            --openapi-spec=openapi2-functions.yaml \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --backend-auth-service-account=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy API Gateway
        run: |
          gcloud api-gateway gateways create data-migration-gateway \
            --api=data-migration-api \
            --api-config=data-migration-config-${{ github.run_number }} \
            --location=us-central1 \
            --project=${{ secrets.GCP_PROJECT_ID }}